sudo: required

services:
  - docker

stages:
  - name: build_and_test
    - docker build -t galapagos_nao .

stages:
  - name: deploy
    # require the branch name to be master
    if: branch = master
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker images
      - docker tag galapagos_nao $DOCKER_USERNAME/galapagos_nao:$TRAVIS_BUILD_NUMBER
      - docker tag galapagos_nao $DOCKER_USERNAME/galapagos_nao:latest
      - docker push $DOCKER_USERNAME/galapagos_nao