sudo: required

services:
  - docker

script:
  - docker build -t galapagos_nao .
  - docker login -u="$DOCKER_USERNAME" --password-stdin="$DOCKER_PASSWORD"
  - docker images
  - docker tag galapagos_nao $DOCKER_USERNAME/galapagos_nao:$TRAVIS_BUILD_NUMBER
  - docker tag galapagos_nao $DOCKER_USERNAME/galapagos_nao:latest
  - docker push $DOCKER_USERNAME/galapagos_nao